### PR TITLE
Working towards 3.0.0.

### PR DESCRIPTION
**Pull request by polytypic**
See #16 and #17 for some background.

### CODE REVIEW

**Comment by polytypic** [comment]
@raimohanska and @milankinen, if you have a moment to look through this pull request and comment it would be cool.

**Comment by milankinen** [comment]
Looks nice! It seems that `partial.lenses` still uses Ramda internally? In that case how about importing only the used ramda functions (`import fn from "ramda/lib/fn"`) so that the final bundle would be smaller?

**Comment by polytypic** [comment]
Hmm... Interesting idea, but if I understand correctly, then importing individual functions from Ramda would only lead to a smaller bundle in case that no other part of the application imports Ramda.  That is because Ramda is built into a [single source file](https://github.com/ramda/ramda/blob/master/dist/ramda.js) and if you import that (`import R from "ramda"`) *and* individual functions (e.g. `import equals from "ramda/src/equals"`) you will effectively get the individual functions twice. Are minifiers intelligent enough to eliminate such duplication?

**Comment by polytypic** [comment]
And thanks for the feedback, @milankinen!

**Pull request merged**
